# Generated by Django 5.2.17 on 2026-09-23 00:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=40)),
                ('target', models.CharField(blank=True, max_length=150)),
                ('result', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('root_department', models.CharField(default='1', max_length=100, verbose_name='钉钉根部门 ID')),
                ('root_ou', models.CharField(blank=True, max_length=500, verbose_name='同步 AD 根 OU DN')),
                ('naming', models.CharField(choices=[('employee_id', '工号'), ('source_id', '钉钉 userId'), ('email', '邮箱前缀')], default='employee_id', max_length=30, verbose_name='新账号命名')),
                ('attributes', models.JSONField(blank=True, default=list, help_text='displayName、mail、title、department、telephoneNumber', verbose_name='同步属性')),
                ('disable_missing', models.BooleanField(default=False, verbose_name='全量同步禁用离职人员')),
                ('disable_limit', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='禁用人数阈值')),
                ('disable_percent', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='禁用比例阈值 %')),
                ('sspr_enabled', models.BooleanField(default=False, verbose_name='开启员工密码重置')),
                ('sspr_match', models.CharField(choices=[('employee_id', '钉钉工号 → AD employeeID'), ('email', '钉钉邮箱 → AD mail'), ('source_id', '钉钉 userId → AD sAMAccountName')], default='employee_id', max_length=30, verbose_name='密码重置匹配方式')),
                ('unlock_after_reset', models.BooleanField(default=False, verbose_name='重置后解锁')),
                ('minimum_password_length', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(128)], verbose_name='最短密码长度')),
                ('schedule_enabled', models.BooleanField(default=False, verbose_name='开启定时同步')),
                ('interval_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5)], verbose_name='同步间隔（分钟）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100, unique=True)),
                ('dn', models.CharField(max_length=500)),
                ('object_guid', models.UUIDField()),
                ('manual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSession',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=100)),
                ('object_guid', models.UUIDField()),
                ('config_fingerprint', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='preview', max_length=20)),
                ('status', models.CharField(default='queued', max_length=30)),
                ('scope', models.CharField(default='full', max_length=20)),
                ('selected', models.JSONField(default=list)),
                ('actor', models.CharField(default='scheduler', max_length=150)),
                ('plan', models.JSONField(default=dict)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('excluded', models.BooleanField(default=False)),
                ('primary_department', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RateWindow',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('root_department', models.CharField(max_length=100)),
                ('users', models.JSONField()),
                ('departments', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=30)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('target_guid', models.UUIDField(null=True)),
                ('evidence', models.JSONField(default=dict)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync_app.job')),
            ],
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_guid', models.UUIDField(unique=True)),
                ('username', models.CharField(max_length=100)),
                ('manual', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('revision', models.UUIDField(default=uuid.uuid4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sync_app.person')),
            ],
        ),
    ]
