# Generated by Django 5.2.17 on 2026-09-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='identity_anchor',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
