# Generated by Django 5.2.17 on 2026-09-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0002_configuration_identity_anchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='protected_usernames',
            field=models.JSONField(blank=True, default=list, help_text='填写服务账号、共享账号等 sAMAccountName；同步和密码重置均禁止操作', verbose_name='额外保护账号'),
        ),
    ]
