# Generated by Django 5.2.17 on 2026-09-23 01:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0003_configuration_protected_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_full_success', models.DateTimeField(null=True)),
                ('connection_checks', models.JSONField(default=dict)),
                ('connections_checked_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='audit',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='clear_attributes',
            field=models.JSONField(blank=True, default=list, help_text='必须属于已启用的同步属性；默认空值不覆盖 AD', verbose_name='允许来源空值清除的属性'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='enable_new_accounts',
            field=models.BooleanField(default=True, verbose_name='新建账号初始化成功后启用'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='match_field',
            field=models.CharField(choices=[('employee_id', '工号（唯一精确匹配可自动绑定）'), ('email', '邮箱（仅建议，需人工确认）'), ('source_id', 'userId 与 AD 账号名（仅建议）')], default='employee_id', max_length=30, verbose_name='同步匹配字段'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='require_password_change',
            field=models.BooleanField(default=True, verbose_name='新建账号首次登录必须改密'),
        ),
        migrations.AddField(
            model_name='employeesession',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
