# Generated by Django 5.2.17 on 2026-09-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0004_runtimestate_audit_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimestate',
            name='last_cleanup_at',
            field=models.DateTimeField(null=True),
        ),
    ]
