# Generated by Django 5.2.17 on 2026-09-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0005_runtimestate_last_cleanup_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'verbose_name': '审计日志', 'verbose_name_plural': '审计日志'},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': '组织配置', 'verbose_name_plural': '组织配置'},
        ),
        migrations.AlterModelOptions(
            name='departmentbinding',
            options={'verbose_name': '部门映射', 'verbose_name_plural': '部门映射'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '同步任务', 'verbose_name_plural': '同步任务'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': '执行记录', 'verbose_name_plural': '执行记录'},
        ),
    ]
