# Generated by Django 5.2.17 on 2026-09-26 15:31

from django.db import migrations, models


def backfill_audit_state(apps, schema_editor):
    audits = apps.get_model("sync_app", "Audit").objects.using(schema_editor.connection.alias)
    audits.filter(state="", action="sspr_reset", success=False, result__contains="结果不明").update(state="unknown")
    audits.filter(state="", action="sspr_reset", success=False, result__startswith="密码已重置，但解锁失败").update(state="partial")
    audits.filter(state="", success=True).update(state="success")
    audits.filter(state="", success=False).update(state="failed")


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0006_alter_audit_options_alter_configuration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='state',
            field=models.CharField(blank=True, choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分完成'), ('pending', '处理未完成'), ('unknown', '待确认')], default='', max_length=16),
        ),
        migrations.RunPython(backfill_audit_state, migrations.RunPython.noop),
    ]
