# Generated by Django 5.2.17 on 2026-10-08 01:14

import django.core.validators
import django.db.models.deletion
import sync_app.models
from django.db import migrations, models


def seed_confirmed_platforms(apps, schema_editor):
    EmployeePageSettings = apps.get_model("sync_app", "EmployeePageSettings")
    AuthPlatform = apps.get_model("sync_app", "AuthPlatform")
    alias = schema_editor.connection.alias
    page_settings, _ = EmployeePageSettings.objects.using(alias).get_or_create(pk=1)
    # Only these names are confirmed; links and password propagation are unset.
    for position, name in enumerate(("VPN", "Nextcloud", "AI知识库")):
        AuthPlatform.objects.using(alias).get_or_create(
            page_settings_id=page_settings.pk, name=name,
            defaults={"authentication_note": "使用企业 AD 账号认证", "position": position},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0009_sspr_audit_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePageSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='重置我的 AD 密码', max_length=100, verbose_name='页面标题')),
                ('description', models.TextField(default='通过钉钉验证身份，查询并重置本人 AD 账号密码。', max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='页面说明')),
                ('announcement', models.TextField(blank=True, max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='公告')),
                ('help_text', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='操作帮助')),
                ('support_text', models.TextField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='联系支持')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '员工页面设置',
                'verbose_name_plural': '员工页面设置',
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='employee_page_settings_singleton')],
            },
        ),
        migrations.CreateModel(
            name='AuthPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='平台名称')),
                ('authentication_note', models.CharField(blank=True, max_length=500, verbose_name='认证说明')),
                ('login_url', models.URLField(blank=True, help_text='仅填写 HTTP 或 HTTPS 地址，不得包含用户名或密码。', max_length=500, validators=[sync_app.models.validate_platform_login_url], verbose_name='登录地址')),
                ('password_note', models.CharField(blank=True, max_length=500, verbose_name='改密生效说明')),
                ('enabled', models.BooleanField(default=True, verbose_name='在员工页面显示')),
                ('position', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='显示顺序')),
                ('page_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='sync_app.employeepagesettings')),
            ],
            options={
                'verbose_name': 'AD 认证平台',
                'verbose_name_plural': 'AD 认证平台',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.RunPython(seed_confirmed_platforms, migrations.RunPython.noop),
    ]
