# Generated by Django 5.2.17 on 2026-10-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0013_password_reset_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='binding',
            name='sync_managed',
            field=models.BooleanField(db_default=True, default=True, verbose_name='已纳入同步管理'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='auto_associate_accounts',
            field=models.BooleanField(db_default=True, default=True, help_text='选择工号 → AD 账号名时，后台默认核验并保存唯一匹配；人工关联优先。关联只保存身份关系，AD 写入仍须按受管范围预览并确认。', verbose_name='自动关联工号对应的 AD 账号'),
        ),
    ]
