# Generated by Django 5.2.17 on 2026-10-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0014_default_account_associations'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='auto_onboard_accounts',
            field=models.BooleanField(db_default=False, default=False, help_text='开启后，同步任务将 LDAP 查询范围内唯一匹配或已关联的普通启用账号，从根 OU 外迁入对应部门并纳入管理。定时同步无需逐人确认；受保护、禁用、排除或身份冲突的账号不迁入。', verbose_name='自动纳管已有 AD 账号'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='auto_associate_accounts',
            field=models.BooleanField(db_default=True, default=True, help_text='选择工号 → AD 账号名时，后台默认核验并保存唯一匹配；人工关联优先。此任务只保存身份关系，实际 AD 写入由同步任务执行。', verbose_name='自动关联工号对应的 AD 账号'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='match_field',
            field=models.CharField(choices=[('employee_id', '钉钉工号 → AD employeeID（唯一精确匹配可自动绑定）'), ('employee_username', '钉钉工号 → AD sAMAccountName（唯一精确匹配可自动绑定）'), ('email', '邮箱（仅建议，需人工确认）'), ('source_id', 'userId 与 AD 账号名（仅建议）')], default='employee_id', help_text='更改匹配方式后须重新生成预览；未开启自动纳管时，AD 根 OU 外的现有账号不会自动纳入同步。', max_length=30, verbose_name='同步匹配字段'),
        ),
    ]
