from __future__ import annotations

DEFAULT_APP_SETTINGS = {
    "group_display_separator": ("-", "string"),
    "group_display_mode": ("compact_path", "string"),
    "group_display_apply_scope": ("new_only", "string"),
    "group_recursive_enabled": ("true", "bool"),
    "schedule_execution_mode": ("apply", "string"),
    "managed_relation_cleanup_enabled": ("false", "bool"),
    "user_ou_placement_strategy": ("source_primary_department", "string"),
    "source_root_unit_ids": ("", "string"),
    "source_root_unit_display_text": ("", "string"),
    "directory_root_ou_path": ("", "string"),
    "disabled_users_ou_path": ("Disabled Users", "string"),
    "job_history_retention_days": ("30", "int"),
    "event_history_retention_days": ("30", "int"),
    "audit_log_retention_days": ("90", "int"),
    "web_bind_host": ("127.0.0.1", "string"),
    "web_bind_port": ("8000", "int"),
    "web_public_base_url": ("", "string"),
    "web_session_cookie_secure_mode": ("auto", "string"),
    "web_trust_proxy_headers": ("false", "bool"),
    "web_forwarded_allow_ips": ("127.0.0.1", "string"),
    "brand_display_name": ("AD Org Sync", "string"),
    "brand_mark_text": ("AD", "string"),
    "brand_attribution": ("微信公众号：大刘讲IT", "string"),
    "web_session_idle_minutes": ("30", "int"),
    "web_login_max_attempts": ("5", "int"),
    "web_login_window_seconds": ("300", "int"),
    "web_login_lockout_seconds": ("300", "int"),
    "web_admin_password_min_length": ("8", "int"),
    "sspr_enabled": ("false", "bool"),
    "sspr_min_password_length": ("12", "int"),
    "sspr_unlock_account_default": ("false", "bool"),
    "sspr_verification_session_ttl_seconds": ("600", "int"),
    "wecom_department_cache_ttl_seconds": ("300", "int"),
    "backup_retention_days": ("30", "int"),
    "backup_retention_max_files": ("30", "int"),
    "high_risk_apply_requires_review": ("true", "bool"),
    "high_risk_review_ttl_minutes": ("240", "int"),
    "offboarding_grace_days": ("0", "int"),
    "offboarding_notify_managers": ("false", "bool"),
    "disable_circuit_breaker_enabled": ("false", "bool"),
    "disable_circuit_breaker_percent": ("5", "float"),
    "disable_circuit_breaker_min_count": ("10", "int"),
    "disable_circuit_breaker_requires_approval": ("true", "bool"),
    "first_sync_identity_claim_mode": ("auto_safe", "string"),
    "managed_group_type": ("security", "string"),
    "managed_group_mail_domain": ("", "string"),
    "custom_group_ou_path": ("Managed Groups", "string"),
    "advanced_connector_routing_enabled": ("false", "bool"),
    "attribute_mapping_enabled": ("false", "bool"),
    "write_back_enabled": ("false", "bool"),
    "custom_group_sync_enabled": ("false", "bool"),
    "offboarding_lifecycle_enabled": ("false", "bool"),
    "field_conflict_queue_enabled": ("false", "bool"),
    "rehire_restore_enabled": ("false", "bool"),
    "custom_group_archive_enabled": ("false", "bool"),
    "scheduled_review_execution_enabled": ("false", "bool"),
    "automatic_replay_enabled": ("false", "bool"),
    "ops_notify_dry_run_failure_enabled": ("false", "bool"),
    "ops_notify_conflict_backlog_enabled": ("false", "bool"),
    "ops_notify_conflict_backlog_threshold": ("5", "int"),
    "ops_notify_review_pending_enabled": ("false", "bool"),
    "ops_notify_rule_governance_enabled": ("false", "bool"),
    "ops_scheduled_apply_gate_enabled": ("true", "bool"),
    "ops_scheduled_apply_max_dry_run_age_hours": ("24", "int"),
    "ops_scheduled_apply_requires_zero_conflicts": ("true", "bool"),
    "ops_scheduled_apply_requires_review_approval": ("true", "bool"),
    "integration_api_token": ("", "string"),
    "future_onboarding_enabled": ("false", "bool"),
    "future_onboarding_start_field": ("hire_date", "string"),
    "contractor_lifecycle_enabled": ("false", "bool"),
    "lifecycle_employment_type_field": ("employment_type", "string"),
    "contractor_end_field": ("contract_end_date", "string"),
    "lifecycle_sponsor_field": ("sponsor_userid", "string"),
    "contractor_type_values": ("contractor,intern,vendor,temp", "string"),
}


ORG_SCOPED_APP_SETTINGS = {
    "group_display_separator",
    "group_display_mode",
    "group_display_apply_scope",
    "group_recursive_enabled",
    "group_recursive_enabled_user_override",
    "schedule_execution_mode",
    "managed_relation_cleanup_enabled",
    "user_ou_placement_strategy",
    "source_root_unit_ids",
    "source_root_unit_display_text",
    "directory_root_ou_path",
    "disabled_users_ou_path",
    "offboarding_grace_days",
    "offboarding_notify_managers",
    "disable_circuit_breaker_enabled",
    "disable_circuit_breaker_percent",
    "disable_circuit_breaker_min_count",
    "disable_circuit_breaker_requires_approval",
    "first_sync_identity_claim_mode",
    "managed_group_type",
    "managed_group_mail_domain",
    "custom_group_ou_path",
    "sspr_enabled",
    "sspr_min_password_length",
    "sspr_unlock_account_default",
    "sspr_verification_session_ttl_seconds",
    "advanced_connector_routing_enabled",
    "attribute_mapping_enabled",
    "write_back_enabled",
    "custom_group_sync_enabled",
    "offboarding_lifecycle_enabled",
    "field_conflict_queue_enabled",
    "rehire_restore_enabled",
    "custom_group_archive_enabled",
    "scheduled_review_execution_enabled",
    "automatic_replay_enabled",
    "ops_notify_dry_run_failure_enabled",
    "ops_notify_conflict_backlog_enabled",
    "ops_notify_conflict_backlog_threshold",
    "ops_notify_review_pending_enabled",
    "ops_notify_rule_governance_enabled",
    "ops_scheduled_apply_gate_enabled",
    "ops_scheduled_apply_max_dry_run_age_hours",
    "ops_scheduled_apply_requires_zero_conflicts",
    "ops_scheduled_apply_requires_review_approval",
    "integration_api_token",
    "future_onboarding_enabled",
    "future_onboarding_start_field",
    "contractor_lifecycle_enabled",
    "lifecycle_employment_type_field",
    "contractor_end_field",
    "lifecycle_sponsor_field",
    "contractor_type_values",
    "last_sync_time",
    "last_sync_success",
}
